version: '3.4'
services:
  db:
    image: atbatw146/mysql-rest-with-spring-boot-devs
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_spring_boot_devs
    ports:
      - "3308:3306"
    networks:
      - devs-network
  rest-with-spring-boot-devs:
    image: atbatw146/rest-with-spring-boot-devs
    restart: always
    build: ./RestWithSpringBootUdemy
    working_dir: /RestWithSpringBootUdemy
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./RestWithSpringBootUdemy:/RestWithSpringBootUdemy
      - ~/.m2:/root/.m2
    ports:
      - "8081:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - devs-network
networks:
    devs-network:
        driver: bridge